#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.2
#  in conjunction with Tcl version 8.6
#    Nov 15, 2022 08:50:46 PM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import requests
import index_support

from persistence import *

enderecoApi = "http://127.0.0.1:5000/api/capitalIntelectual"

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.117, rely=0.111, height=21, width=64)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Registro''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.117, rely=0.178, height=21, width=34)
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Tema''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.117, rely=0.244, height=21, width=54)
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Descrição''')

        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.117, rely=0.311, height=21, width=54)
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Autores''')

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.233, rely=0.111, height=20, relwidth=0.273)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Entry1_1 = tk.Entry(self.top)
        self.Entry1_1.place(relx=0.233, rely=0.178, height=20, relwidth=0.273)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="black")
        self.Entry1_1.configure(insertbackground="black")
        self.Entry1_1.configure(selectbackground="blue")
        self.Entry1_1.configure(selectforeground="white")

        self.Entry1_1_1 = tk.Entry(self.top)
        self.Entry1_1_1.place(relx=0.233, rely=0.244, height=20, relwidth=0.273)
        self.Entry1_1_1.configure(background="white")
        self.Entry1_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1_1.configure(font="TkFixedFont")
        self.Entry1_1_1.configure(foreground="#000000")
        self.Entry1_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1_1.configure(highlightcolor="black")
        self.Entry1_1_1.configure(insertbackground="black")
        self.Entry1_1_1.configure(selectbackground="blue")
        self.Entry1_1_1.configure(selectforeground="white")

        self.Entry1_1_1_1 = tk.Entry(self.top)
        self.Entry1_1_1_1.place(relx=0.233, rely=0.311, height=20
                , relwidth=0.273)
        self.Entry1_1_1_1.configure(background="white")
        self.Entry1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1_1_1.configure(font="TkFixedFont")
        self.Entry1_1_1_1.configure(foreground="#000000")
        self.Entry1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1_1_1.configure(highlightcolor="black")
        self.Entry1_1_1_1.configure(insertbackground="black")
        self.Entry1_1_1_1.configure(selectbackground="blue")
        self.Entry1_1_1_1.configure(selectforeground="white")

        self.Listbox1 = tk.Listbox(self.top)
        self.Listbox1.place(relx=0.017, rely=0.378, relheight=0.604
                , relwidth=0.957)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")

        self.Button1 = tk.Button(self.top, command=self.btnSalvar_Click)
        self.Button1.place(relx=0.533, rely=0.267, height=44, width=77)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Salvar''')

        self.Button2 = tk.Button(self.top, command=self.btnListar_Click)
        self.Button2.place(relx=0.833, rely=0.267, height=44, width=77)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(compound='left')
        self.Button2.configure(cursor="fleur")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Listar''')

    def btnSalvar_Click(self):
        registro = self.Entry1.get()
        tema = self.Entry1_1.get()
        descricao = self.Entry1_1_1.get()
        autor = self.Entry1_1_1_1.get()

        capital_intelectual = {
            "registro": registro,
            "tema": tema,
            "descricao": descricao,
            "autor": autor
        }

        requests.post(enderecoApi, json=capital_intelectual)

    def btnListar_Click(self):
        response = requests.get(enderecoApi)

        self.Listbox1.delete(0, END)
        self.Listbox1.insert(0, response.json())

def start_up():
    index_support.main()

if __name__ == '__main__':
    index_support.main()




